### ISSUE TITLE
Invalid Mashape Key

### ISSUE THREAD

**Issue by TheEvilSocks** [richard1/ani-up#1]
`
{ message: 'Invalid Mashape Key' }
`
Is returned every time I request something using the hummingbird api using your module.

**Comment by richard1** [comment]
It looks like there's an issue with your Hummingbird API key.  These are generated from [Mashape](https://market.mashape.com/vikhyat/hummingbird-v1), so make sure your `creds.js` file has some line like:

```
creds.HUMMINGBIRD_API_KEY = "your actual key here"
```

where that string is replaced with your actual key.

Another thing to note is that we're currently using Hummingbird's v1 API (not v2).

**Comment by richard1** [comment]
@TheEvilSocks I'll go ahead and assume this issue is resolved!  Feel free to reopen if you're still experiencing issues.
